// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    repositories {
        google()
    }
    dependencies {

     // classpath 'com.google.gms:google-services:4.3.15'
       // classpath 'com.android.tools.build:gradle-core:3.1.4'
       // classpath "com.android.tools.build:gradle:8.13.0"
        def nav_version = "2.5.3"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"



    }
}



plugins {
    //8.0.1
    //
    // id 'com.android.application' version '8.0.1' apply false
    // id 'com.android.library' version '8.0.1' apply false

    // 👈 استخدام إصدار مستقر وموجود بالفعل من AGP
    id 'com.android.application' version '8.2.2' apply false
    id 'com.android.library' version '8.2.2' apply false

    // 👈 ترقية Kotlin إلى إصدار يدعم JVM 17/21
    id 'org.jetbrains.kotlin.android' version '1.9.23' apply false

    id 'com.google.gms.google-services' version '4.3.15' apply false
}

